
apiVersion: v1
kind: Namespace
metadata:
  name: poncetapp-demo

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-demo
  namespace: poncetapp-demo
data:
  application_port: "8000"

---

apiVersion: apps/v1
kind: Deployment
metadata:  
  name: nodejs-deployment  
  labels:    
    app: helloworld
    namespace: poncetapp-demo
spec:  
  replicas: 1  
  selector:    
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec: 
     containers:
      - name: helloworld
        image: germanium/nodejs-helloworld
        ports:
        - containerPort: 8000
---

kind: Service
apiVersion: v1
metadata:
  name: nodejs-service
  namespace: poncetapp-demo
spec:
  selector:
    app: helloworld
  ports:
    - port: 8000        


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
  namespace: poncetapp-demo
spec:
  rules:
  - http:
      paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service: 
              name: nodejs-service
              port: 
                number: 8000